from app.database.history.queries import HISTORY_INIT_STATEMENTS, HISTORY_QUERIES
from app.database.iterations.queries import ITERATION_INIT_STATEMENTS, ITERATION_QUERIES
from app.database.organizations.queries import ORGANIZATION_INIT_STATEMENTS, ORGANIZATION_QUERIES
from app.database.teams.queries import TEAM_INIT_STATEMENTS, TEAM_QUERIES
from app.database.users.queries import USER_INIT_STATEMENTS, USER_QUERIES  # noqa
from app.database.work_items.queries import WORK_ITEM_INIT_STATEMENTS, WORK_ITEM_QUERIES

INIT_STATEMENTS = (
    []
    + ORGANIZATION_INIT_STATEMENTS
    + ITERATION_INIT_STATEMENTS
    + TEAM_INIT_STATEMENTS
    + WORK_ITEM_INIT_STATEMENTS
    + HISTORY_INIT_STATEMENTS
)

QUERIES = {
    **USER_QUERIES,
    **WORK_ITEM_QUERIES,
    **ORGANIZATION_QUERIES,
    **ITERATION_QUERIES,
    **TEAM_QUERIES,
    **HISTORY_QUERIES,
}
