from app.database.work_items.queries import WORK_ITEM_INIT_STATEMENTS, WORK_ITEM_QUERIES
from app.database.users.queries import USER_INIT_STATEMENTS, USER_QUERIES

INIT_STATEMENTS = [] + WORK_ITEM_INIT_STATEMENTS + USER_INIT_STATEMENTS

QUERIES = {**WORK_ITEM_QUERIES, **USER_QUERIES}


