from app.database.organizations.queries import ORGANIZATION_INIT_STATEMENTS, ORGANIZATION_QUERIES
from app.database.users.queries import USER_INIT_STATEMENTS, USER_QUERIES
from app.database.work_items.queries import WORK_ITEM_INIT_STATEMENTS, WORK_ITEM_QUERIES

INIT_STATEMENTS = [] + WORK_ITEM_INIT_STATEMENTS + USER_INIT_STATEMENTS + ORGANIZATION_INIT_STATEMENTS

QUERIES = {**WORK_ITEM_QUERIES, **USER_QUERIES, **ORGANIZATION_QUERIES}
